# application.yml
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
  http2:
    enabled: true

spring:
  application:
    name: text-analysis-app
  profiles:
    active: dev

app:
  text-analysis:
    chunk-size: 1000
    chunk-overlap: 50
    thread-pool-size: 10
    max-file-size: 100MB
    request-timeout: 300s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

logging:
  level:
    com.textanalysis: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

